---
global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
    - targets:
      - prometheus_main:9090

  - job_name: nodes
    scrape_interval: 5s
    static_configs:
    - targets:
      - 192.168.56.91:9100
      - 192.168.56.41:9100
      - 192.168.56.42:9100

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets:
      - 192.168.56.91:8081
      - 192.168.56.41:8081
      - 192.168.56.42:8081
