---
version: "3"
services:
  ghost:
    container_name: ghost
    image: ghost:4-alpine
#    restart: always
    ports:
      - 80:2368
    environment:
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: ghost
      database__connection__password: ghostpass
      database__connection__database: ghostdb
    volumes:
      - ghost-volume:/var/lib/ghost
    networks:
      - ghost_network
      - mysql_network
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: mysql
    image: mysql:8.0
#    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghostpass
      MYSQL_DATABASE: ghostdb
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - mysql_network
    healthcheck:
      test: "mysql -u $$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE -e 'SELECT 1;'"
      interval: 1s
      retries: 60

volumes:
  ghost-volume:
  mysql-volume:

networks:
  ghost_network:
  mysql_network:
