---
version: "3.9"
services:
  web:
    image: "nginx:alpine"
    ports:
      - "8082:80"
    volumes:
      - nginx_html:/usr/share/nginx/html/
    links:
      - redis
  redis:
    image: "redis:alpine"
volumes:
  nginx_html: {}
