# -*- mode: ruby -*-
# vi: se ft=ruby :

ENV["LC_ALL"] = "en_US.UTF-8"
MASTER_NODE_COUNT = 1
WORKER_NODE_COUNT = 2

$script = <<-SCRIPT
sudo sed -re "s/^(\#?)([[:space:]]?)PasswordAuthentication([[:space:]]+)no/PasswordAuthentication yes/" -i /etc/ssh/sshd_config
sudo sed -re "s/^(\#?)([[:space:]]?)PasswordAuthentication([[:space:]]+)yes/PasswordAuthentication yes/" -i /etc/ssh/sshd_config
service sshd restart
sleep 5
SCRIPT

# Grab the name of the default interface
default_network_interface = `ip route | awk '/^default/ {printf "%s", $5; exit 0}'`

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    
    # Use the same key for each machine
    # config.ssh.insert_key = false

    # Create the Master nodes
    (1..MASTER_NODE_COUNT).each do |i|
        config.vm.define "master#{i}" do |master|
            master.vm.hostname = "master#{i}.example.com"
            master.vm.network "private_network", ip: "192.168.56.#{90 + i}"
            master.vm.network "public_network", bridge: "#{default_network_interface}"

            master.vm.provider "virtualbox" do |vbox|
                vbox.name = "master#{i}"
                vbox.memory = 2048
                vbox.cpus = 2
            end

            master.vm.provision "shell" do |s|
                s.inline = $script
            end
        end
    end

    # Create the Worker nodes
    (1..WORKER_NODE_COUNT).each do |i|
        config.vm.define "worker#{i}" do |worker|
            worker.vm.hostname = "worker#{i}.example.com"
            worker.vm.network "private_network", ip: "192.168.56.#{40 + i}"
            worker.vm.network "public_network", bridge: "#{default_network_interface}"

            worker.vm.provider "virtualbox" do |vbox|
                vbox.name = "worker#{i}"
                vbox.memory = 2048
                vbox.cpus = 2
            end
 
            worker.vm.provision "shell" do |s|
                s.inline = $script
            end
        end
    end
end
